
title: MKBRNS - User Interface Designer
email: hello@mikebnrs.com
description: >- # this means to ignore newlines until "baseurl:"
  Michael Burns Portfolio
baseurl: "/lumad" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mikeburnsuiux
github_username:  mikeburnsuiux

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed
  
collections:
  portfolio:
    output: true
    permalink: /:path/

